version: "3.3"
services:
  mongodb:
    image : mongo
    container_name: course_guide_mongodb
    environment:
      MONGO_INITDB_DATABASE: course_guide
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: project123
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '8081:8081'
    restart: unless-stopped