version: "3.8"
services:
  mongodb:
    image : mongo:latest
    container_name: course_guide_mongodb
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - ${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}
    volumes:
      #- ./mongo-volume:/data/db
      - ./mongo-volume:/var/lib/mongo
    #ports:
   #   - '27017:27017'
    restart: unless-stopped